name: Publish pre-release package

# This workflow will publish a release every night if changes have been made.

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

concurrency:
  group: "pre-release"
  cancel-in-progress: true

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit is less than 24h old

    strategy:
      matrix:
        python-version: ["3.8"]

    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}

    # https://github.com/orgs/community/discussions/27128
    steps:
      - uses: actions/checkout@v2
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  pre_release:
    name: "Pre Release"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.8"]

    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
      - name: Tell Pants to use Python ${{ matrix.python-version }}
        run: 'echo "PY=python${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=[''==${{ matrix.python-version
          }}.*'']" >> $GITHUB_ENV
          '
      - name: Initialize Pants
        uses: pantsbuild/actions/init-pants@main
        with:
          # cache0 makes it easy to bust the cache if needed
          gha-cache-key: cache0-py${{ matrix.python_version }}
          named-caches-hash: ${{ hashFiles('pants-plugins/lock.txt') }}
          pants-python-version: ${{ matrix.python_version }}          # cache0 makes it easy to bust the cache if needed

      - name: Build Packages
        run: "./pants package ::"

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: ${{ github.ref }}
          configuration: .github/workflows/changelog.json


      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          prerelease: true
          title: "Nightly release"
          tag_name: "latest"
          files: |
            dist/pants*
            LICENSE-*
