name: Release
on:
  push:
    tags:
      - v*

jobs:
  create-release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Fetch tags
      run: git fetch --prune --unshallow --tags

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python_version }}
    - name: Tell Pants to use Python ${{ matrix.python-version }}
      run: 'echo "PY=python${{ matrix.python-version }}" >> $GITHUB_ENV
        echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=[''==${{ matrix.python-version
        }}.*'']" >> $GITHUB_ENV
        '

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache0-py${{ matrix.python_version }}
        named-caches-hash: ${{ hashFiles('pants-plugins/lock.txt') }}
        pants-python-version: ${{ matrix.python_version }}          # cache0 makes it easy to bust the cache if needed

    - name: "Build Changelog"
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v3.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        toTag: ${{ github.ref_name }}
        configuration: .github/workflows/changelog.json

    - name: Build Packages
      run: "./pants package //:package"

    - name: Release to GitHub
      uses: mikepenz/action-gh-release@v0.2.0-a03
      with:
        body: ${{ steps.github_release.outputs.changelog }}
        prerelease: false
        tag_name: ${{ github.ref }}
        name: "Release ${{ github.ref_name }}"
        files: |
          dist/pants*
          LICENSE-*

    - name: Publish Packages to PyPi
      env:
        TWINE_PASSWORD_PYPI: ${{ secrets.PYPI }}
        TWINE_USERNAME_PYPI: __token__

      run: ./pants publish //:package
